### ISSUE TITLE
出现题目时一直刷新页面而非自动答题

### ISSUE THREAD

**Issue by ChinaYong** [zly2006/yuketang-auto-answer#1]
如题，在雨课堂出现题目时不会自动答题，会一直刷新页面直到我手动答完题为止。

不过调试信息能够正常显示题目和答案的信息

**Comment by zly2006** [comment]
会在之后更改刷新方式，不再使用location.reload()

然后你能否提供一下调试信息

**Comment by ChinaYong** [comment]
[调试信息.txt](https://github.com/zly2006/yuketang-auto-answer/files/15273805/default.txt)
这是一个课程中的调试信息，我直接复制粘贴到了txt文件中，不知道是不是你想要的

**Comment by zly2006** [comment]
好的。我简单看了一下，这个问题会在之后修复，主要是不再用location.reload刷新，然后会发布新版本。

**Comment by ChinaYong** [comment]
静候佳音🫡

**Comment by zly2006** [comment]
对单选和多选更新了逻辑，正在审核。你可以自己通过源码build一个体验。 bfc2551

**Comment by zly2006** [comment]
看看好用不，好用给个5星好评 :D
